const actions = {
  authUser: {
    SET_AUTH_USER: 'SET_AUTH_USER',
    UNSET_AUTH_USER: 'UNSET_AUTH_USER',
  },
  isPreload: {
    SET_IS_PRELOAD: 'SET_IS_PRELOAD',
  },
  users: {
    GET_USERS: 'GET_USERS',
    REGISTER_USERS: 'REGISTER_USERS',
  },
  threads: {
    GET_THREADS: 'GET_THREADS',
    ADD_THREAD: 'ADD_THREAD',
    UP_VOTE: 'UP_VOTE',
    DOWN_VOTE: 'DOWN_VOTE',
    NEUTRAL_VOTE: 'NEUTRAL_VOTE',
    RESTORE_VOTE: 'RESTORE_VOTE',
  },
  threadDetail: {
    GET_THREAD_DETAIL: 'GET_THREAD_DETAIL',
    CLEAR_THREAD_DETAIL: 'CLEAR_THREAD_DETAIL',

    UP_VOTE_DETAIL: 'UP_VOTE_DETAIL',
    DOWN_VOTE_DETAIL: 'DOWN_VOTE_DETAIL',
    NEUTRAL_VOTE_DETAIL: 'NEUTRAL_VOTE_DETAIL',
    RESTORE_VOTE_DETAIL: 'RESTORE_VOTE_DETAIL',

    UP_VOTE_COMMENT: 'UP_VOTE_COMMENT',
    DOWN_VOTE_COMMENT: 'DOWN_VOTE_COMMENT',
    NEUTRAL_VOTE_COMMENT: 'NEUTRAL_VOTE_COMMENT',
    RESTORE_VOTE_COMMENT: 'RESTORE_VOTE_COMMENT',
    ADD_COMMENT: 'ADD_COMMENT',
  },
  categories: {
    SET_CATEGORIES: 'SET_CATEGORIES',
    TOGGLE_CATEGORY_SELECTION: 'TOGGLE_CATEGORY_SELECTION',
  },
};
export default actions;
